### ISSUE TITLE
Archiving checked tasks?

### ISSUE THREAD

**Issue by williamabrwolf** [klauscfhq/taskbook#101]
How do I archive checked tasks? Ie remove them from the list?

**Comment by soulseekah** [comment]
This would be useful. My list has grown considerably and I'm fed up of deleting/archiving items manually.

**Comment by soulseekah** [comment]
Looks like this is now available using the new `--clear` flag in 0.2.0

**Comment by klauscfhq** [comment]
Fixed on #43
