### ISSUE TITLE
Command completion for zsh or bash.

### ISSUE THREAD

**Issue by losymear** [klauscfhq/taskbook#104]
If I want to check a task, I have to run `tb -i` first to find the task id.
Hope if I run `tb -c` and enter tab, my terminal can display tasks with ids so I can easily choose the right id. Same for other commands.

**Comment by mastern2k3** [comment]
I started workshopping a plugin for zsh if anyone's still interested
https://github.com/mastern2k3/taskbook-zsh-plugin
