### ISSUE TITLE
Running Taskbook thru watch disables colors

### ISSUE THREAD

**Issue by reaktivo** [klauscfhq/taskbook#19]
**Is your feature request related to a problem? Please describe.**
Terminal colors get disabled when running thru unix watch (at least on a Mac)

**Describe the solution you'd like**
Terminals colors should still be displayed when running `watch` with the `--color` option set.

**Additional context**

The tab on to is running `watch --color tb`, while the one on the bottom is simply running `tb`

<img width="666" alt="screen shot 2018-08-01 at 13 50 33" src="https://user-images.githubusercontent.com/13637/43520059-f01d1aee-9591-11e8-9977-da5af8ff292f.png">

**Comment by gustavopaes** [comment]
Try `watch --color 'tb --color'`. At on ubuntu I get colored output

![screenshot from 2018-08-01 10-07-06](https://user-images.githubusercontent.com/227400/43523415-b1ab72fc-9572-11e8-8376-8ac36fda7655.png)

**Comment by tuandm** [comment]
@gustavopaes I tried `watch --color 'tb --color' on Macbook but it didn't show colors.

**Comment by chrissinclairedited** [comment]
FWIW if you're willing to use `fswatch` rather than `watch`, you can do:

```sh
clear && tb; fswatch -0 ~/.taskbook/storage | xargs -0 -n 1 sh -c 'clear; tb'
```

to get the watch functionality but only updating when the data updates. I've been running that on a mac and the colours all work well:
![screen shot 2018-08-02 at 13 37 17](https://user-images.githubusercontent.com/39764468/43584077-409d5cb4-9659-11e8-804a-d81aedacfba4.png)

**Comment by tuandm** [comment]
@chrissinclairedited Thank you, works like a charm 👍

**Comment by ashinzekene** [comment]
@chrissinclairedited pls what font is that?

**Comment by chrissinclairedited** [comment]
Hi @ashinzekene - It's IBM Plex Mono Medium Italic - https://github.com/IBM/plex.

**Comment by ashinzekene** [comment]
Thanks. Its looking really nice. Nicer than when I used it

**Comment by klauscfhq** [comment]
Closing, for now, will reopen if needed in the future.

**Comment by waldauf** [comment]
Hello,
here I found out how to work taskbook with watch and have colored output. But at first I checked help output and there I didn't find `--color` option:
```
$ taskbook -h | grep color
$
```
Can you add it to taskbook?

Many THX
