### ISSUE TITLE
Error in fresh install

### ISSUE THREAD

**Issue by makeclean** [klauscfhq/taskbook#2]
Starting from a fresh Ubuntu Xenial install, 
```
$> sudo npm install --global taskbook
```
```
$> tb --help
/usr/bin/env: ‘node’: No such file or directory
```
```
sudo ln -s  /usr/bin/nodejs /usr/bin/node
```
```
$> tb --help
/usr/local/lib/node_modules/taskbook/node_modules/meow/index.js:66
	const {pkg} = options;
```
Any ideas?

**Comment by sameet** [comment]
Got exact same issue.

**Comment by gustavopaes** [comment]
check your node version

**Comment by jusopi** [comment]
There should be a note in the readme.md file that states this.

**Comment by gustavopaes** [comment]
maybe should be node >= 8 like this issue #1

**Comment by makeclean** [comment]
Yup, that was it - upgraded using https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version - then worked like a charm! Thanks!
