### ISSUE TITLE
check uncheck tasks

### ISSUE THREAD

**Issue by matthiasdebernardini** [klauscfhq/taskbook#27]
**Describe the bug**
when you check an item that has already been checked the program returns item checked even though it actually becomes unchecked

**To Reproduce**
$ tb -t foo
$tb -c 1
$tb -c 1

**Expected behavior**
If I realized that what I had done wasn't actually done I would want to uncheck it so the program should return "# unchecked" if I run --check twice on an item

**Screenshots**

**Technical Info (please complete the following information)**
 - OS: macOS (10.13.6)
 - Node.js Version: v8.11.3
 - Taskbook Version: 0.1.1

**Additional context**

**Comment by ashinzekene** [comment]
I will create a pull request for this
