### ISSUE TITLE
Taskbook Directory doesn't support tilde home shortcut

### ISSUE THREAD

**Issue by taylorthurlow** [klauscfhq/taskbook#3]
**Describe the bug**
Using `~` to represent my home directory in the `taskbookDirectory` configuration option doesn't work.

**To Reproduce**
* Set `taskbookDirectory` to a path like `/Users/my_username/Dropbox/Taskbook`
* Run `tb`, and observe that Taskbook works as expected
* Set `taskbookDirectory` to a path like `~/Dropbox/Taskbook`
* Run `tb`, and observe that Taskbook says: `Custom app directory was not found on your system: ~/Dropbox/Taskbook`

**Expected behavior**
The Taskbook directory, when using a tilde, should expand to `/Users/my_username/Dropbox/Taskbook`.

**Technical Info (please complete the following information)**
 - OS: macOS 10.13.6
 - Node.js Version: `10.7.0`
 - Taskbook Version: `0.1.1`

**Comment by elliotboney** [comment]
This would be awesome!
