### ISSUE TITLE
How to customize theme

### ISSUE THREAD

**Issue by hushicai** [klauscfhq/taskbook#30]
In `Solarized Dark` mode:

![image](https://user-images.githubusercontent.com/1249423/43557068-83d86e3e-9635-11e8-89f0-875d095965af.png)

Is there some ways to change theme?

**Comment by duynguyenhoang** [comment]
@hushicai Please check my PR https://github.com/klauscfhq/taskbook/pull/34

**Comment by marcelpaulo** [comment]
I've just installed taskbook, was learning how to use it, and found odd that the task ids were not shown:
![image](https://user-images.githubusercontent.com/10074769/43704582-7139b2de-9936-11e8-86ce-6d6b1908bedd.png)

Then realized it might have something to do with the color theme. I'm running `xfce4-terminal` with the built-in `Solarized (dark)` theme, which makes my output even more invisible than @hushicai's.

I'm looking forward to your PR #34 being accepted and merged, @duynguyenhoang. As it is right now, taskbook is not usable on Solarized dark terminals.

I'm running git master (9c97de7) with nodejs 10.8.0-1nodesource1 on Xubuntu 18.04.
