### ISSUE TITLE
How can I generate a picture from taskbook

### ISSUE THREAD

**Issue by focus7eleven** [klauscfhq/taskbook#32]
https://github.com/klauscfhq/taskbook/blob/master/media/header-boards.png

Just like the image above, is there any tool to generate a picture from terminal output?

**Comment by duynguyenhoang** [comment]
In my opinion, you simply use any software which can take the screenshot.

**Comment by focus7eleven** [comment]
@duynguyenhoang Thanks for your help.
But actually what I want is exactly the same as the picture above.
I think it is done in Hyper.js, with a special theme which can hide the address in the status bar, and of course, with cmd+shift+4.

**Comment by 2case** [comment]
Looks more like iTerm2 (in Dark Mode), Window manually resized and taken an Screenshoot with the macOS build in Tools...

**Comment by klauscfhq** [comment]
Screenshots display the [hyper terminal](https://hyper.is) along with the [hyperocean](https://github.com/klauscfhq/hyperocean) theme and the [hyper-hide-title](https://www.npmjs.com/package/hyper-hide-title) plugin : )
