### ISSUE TITLE
Publish debian package?

### ISSUE THREAD

**Issue by kalexmills** [klauscfhq/taskbook#38]
**Is your feature request related to a problem? Please describe.**
This is a neat app and it clearly solves a useful problem (based on the response).

But the command line is ubiquitous and not all cli users are javascript devs who have / want to have npm installed.

**Describe the solution you'd like**
Come up with a way to remove the dependency on npm, using either existing transpilation tools to create binaries or via a port(?)

Port is less favorable option in my opinion, but I'm not enough of a JavaScript developer to be aware of options for creating binaries.

**Additional context**
This would also permit the creation of a lean debian package so those of us on *buntu could just `apt-get install taskbook` without pulling in dependencies. It further would increase the exposure of this nifty tool.

EDIT: Clearly there are stable options for binary releases. Issue is now whether debian packages are merited / desirable.

**Comment by kalexmills** [comment]
Yeah, of course the JS community has solved this problem 🤦‍♂️ 

https://www.npmjs.com/package/pkg

Any plans from project maintainers to publish a debian package? I'm interested in possibly doing so / adding it to travis-ci if there is a need.

**Comment by rjoydip** [comment]
@kalexmills You can check out @klauscfhq https://github.com/klauscfhq/tusk desktop application
