### ISSUE TITLE
[Feature Request] Clean or Clear command to delete checked items

### ISSUE THREAD

**Issue by tmyers273** [klauscfhq/taskbook#40]
**Describe the solution you'd like**
A command that can be run to clean or clear all checked items. This would simply loop through and delete all checked items.

`tb --clear` or `tb --clean`

**Additional context**
I like to start my work day with a clean to do list. Meaning, there is no checked tasks on the board. Currently, I am accomplishing this by manually deleting all checked tasks
`tb -d 113 115 116 117 120 121`

But that approach is error prone. It is too easy to type an incorrect id.

By the way, LOVE the tool! Been using it daily since it was posted on HN a few days ago!

**Comment by JoshuaCrocker** [comment]
+1 I would be willing to give this a go

**Comment by jadiaz** [comment]
another possible option `tb --archive --checked` so as not to have to introduce a new keyword

**Comment by rjoydip** [comment]
@jadiaz good but each time you have to both the flags and alise.

**Comment by casidiablo** [comment]
Also, --archive right now means, confusingly, "list archived items". So --archive --checked sounds to me like "list checked archived items"

**Comment by eckdanny** [comment]
@casidiablo Agree. Care to mention or upvote in #72?

A batch `for task in tasks { remove if completed }` command would be nice.
