### ISSUE TITLE
Command tb not available

### ISSUE THREAD

**Issue by janbaer** [klauscfhq/taskbook#62]
**Describe the bug**
I just have installed taskboard on my machine with npm install -g but after the successful installation the command **tb** was not found. I just use node with nvm, both other globally installed node commandline tools have no problems with that.

I checked the global bin folder where all executable node binaries are installed but no tb binary was there. (It's with nvm under ~/.nvm/versions/node/v10.4.1/bin

I checked 

**To Reproduce**
Just install it with npm -g

**Expected behavior**

**Screenshots**

**Technical Info (please complete the following information)**
- OS: Linux Ubuntu 16.04
- Node.js Version: 10.4.3
- Taskbook Version: latest
- nvm version 0.33

**Comment by foksh** [comment]
I'm having the exact same issue:
**npm install -g taskbook**
/home/XXX/.nvm/versions/node/v6.10.3/lib/node_modules/node/bin/tb -> /home/XXX/.nvm/versions/node/v6.10.3/lib/node_modules/node/lib/node_modules/taskbook/cli.js
\+ taskbook@0.1.1
added 122 packages from 41 contributors in 1.239s

**tb**
tb: command not found

**npm -v**
5.7.1

**nvm --version**
0.33.2

**node -v**
v9.5.0

**cat /etc/os-release** 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

**Comment by rjoydip** [comment]
@foksh your nvm version using node `.nvm/versions/node/v6.10.3` but `taskbook` needs node verison >=6

**Comment by rjoydip** [comment]
@janbaer Install it by `sudo`

**Comment by janbaer** [comment]
@rjoydip This won't work for me since I've no global node version installed. Since I use nvm it's only know with for myself but not with sudo. The benefit is, that normally I never have to use sudo for installing global npm modules and I can switch easily between the node versions since I need different versions for the projects I'm working on.

**Comment by janbaer** [comment]
It was my fault, I just installed accidentally taskboard instead of taskbook since it's also a valid npm package I didn't realize my mistake. Now I installed the right package and it's working fine.
