### ISSUE TITLE
Error While Installing For the first Time

### ISSUE THREAD

**Issue by ahmedofali** [klauscfhq/taskbook#65]
**Describe the bug**
A clear and concise description of what the bug is
![image](https://user-images.githubusercontent.com/22732463/43684097-06470806-989a-11e8-9321-8e5f684ea01e.png)
.

**To Reproduce**
Running Docker Container from node:8.10.0-stretch image.
then Running `npm install --global taskbook`

**Technical Info **
 - OS: Host Windows, vm docker node:8.10.0-stretch
 - Node.js Version: 8.10.0
 - Taskbook Version: latest

**Comment by rjoydip** [comment]
Can you reproduce full debug log

**Comment by ahmedofali** [comment]
that's wired but after stopping the machine and launching it, it worked just fine. it's working right now.

**Comment by rjoydip** [comment]
Fine. Sometimes this happens in `npm`.
