### ISSUE TITLE
-v command doesn't show version information

### ISSUE THREAD

**Issue by alichtman** [klauscfhq/taskbook#7]
**Describe the bug**

`$ tb -v` doesn't show version information.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/20600565/43501096-dd3f8918-9521-11e8-9889-3254cccdc66b.png">

<img width="553" alt="image" src="https://user-images.githubusercontent.com/20600565/43501101-e4433a48-9521-11e8-8227-0b82ef9896d3.png">

**Technical Info (please complete the following information)**
 - OS: MacOS High Sierra, 10.13.6
 - Node.js Version: v10.6.0
 - Taskbook Version: 0.1.1

**Comment by klauscfhq** [comment]
Fixed on #14.
