### ISSUE TITLE
Interpret ~ for taskbookDirectory for specifying paths relative to the home directory.

### ISSUE THREAD

**Issue by bdalton** [klauscfhq/taskbook#91]
**Is your feature request related to a problem? Please describe.**
I'd like to put the taskbook storage inside ~/.config/taskbook. But I get the error "Custom app directory was not found on your system" when I do this. It works when I manually expand ~ to my home directory.

This is more of a hiccup during setup than a deal-breaker. The description on the github landing page uses ~, so it was confusing when the application didn't support it.

I love the application!

**Comment by klauscfhq** [comment]
The issue has been fixed on PR https://github.com/klauscfhq/taskbook/pull/35. New release delivering it will be out soon : )
